import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export const metadata = {
  title: {
    default: "Next.js Tutorial", // fallback title when any child page doesn't provide a title
    template: "%s | Next.js Tutorial", // To add prefix or suffix to the child routes title, %s is the title of the child route
    absolute: "", // absolute title will override the default and template of parent route
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "1rem", backgroundColor: "lightblue" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "lightblue" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
